### ISSUE TITLE
Failover to slave ardb's if the main ardb is failing

### ISSUE THREAD

**Issue by robvanmieghem** [zero-os/0-Disk#38]
- [x] tlog : add nbdserver's ardb slave config to server (#270)
- [x] tlog : also flush (using tlogreplay) to ardb slave in async way (#270)
- [x] tlog : on (re) start, make sure to keep ardb slave synced (#282)
- [x] tlog : add command to sync the ardb slave (#277 )
- [x] tlog : slave syncer must be able to self heal in case of error (#282)
- [x] nbdserver : detect failed master (#278)
- [x] nbdserver : ask tlogserver to sync the slave, need to pause/reject all operations during this sync process (#278)
- [x] nbdserver : switch to ardb slave, may need to restart vdisk or clean all of it's data/cache (#278)
- [x] nbdserver : notify the orchestrator about this failover (moved to #284)
- [x] slave syncer : add hot reload support (#25)

Redis replication is asynchronous, leaving a window for dataloss. I don't want to introduce paxos (or variation upon) complexity so a scenario in which the tlog server is integrated to handle this window seems like a better approach.

**Comment by GlenDC** [comment]
@robvanmieghem I want to (try to) help you with thinking about a solution for this issue. I was wondering if you could give some more information on when, where and why we use this feature?

Also are the slaves read-only or do they write as well? Could you also tell more about how the replication setup is configured at the moment?

**Comment by GlenDC** [comment]
I don't have too many details about our configuration and setup, so I can't elaborate too much yet. I do however think that we'll never be able to have strong consistency with a 100% _redis_-backed solution. Still, _redis_ has a couple of tricks and tools that might be able to assist us...

The [`WAIT`](https://redis.io/commands/wait) _redis_ command can make the client-side synchronous, which would solve the first half of _strong consistency_.

The second property could be partly solved, using [`redis-sentinel`](https://redis.io/topics/sentinel). It could help us with monitoring, notifying, discovery and even auto-recovering in case of failure. Auto-recovering in the sense that it can promote a slave to master in case the master fails. Also if one slave fails it shouldn't be an issue as long as we have enough other slaves. If a master and slave fails, it should still not be an issue (I think), as long as we still have a couple of other slaves available.

**Comment by robvanmieghem** [comment]
As discussed on Telegram, solving it through normal master/slave replication will be hard to do. Better to include the tlog server in the architecture and let that one fill the slaves.

**Comment by iwanbk** [comment]
was planning to check this issue today, but see that this issue moved to alpha-4.
Is it really OK to move it to alpha-4?

**Comment by GlenDC** [comment]
I thought we might not have time for this anymore, but if you think it can fit in, feel free to move it back to alpha-3 and work on it. Perhaps I was a bit too quick to move it to alpha-4. The reason I did is, because alpha-3 is really packed with many issues, most of which were assigned in the middle of the milestone.

**Comment by iwanbk** [comment]
> As discussed on Telegram, solving it through normal master/slave replication will be hard to do. Better to include the tlog server in the architecture and let that one fill the slaves.

Instead of **fill** the slaves, we can also use tlog to **assist** the slaves.

So, we can setup a slave, like the original plan. When the master is failing, we execute `tlogreplay` for the last X minutes. This way, the recovery will be much faster.

But if we don't have time constraint, we can simply do `tlogreplay` from the beginning.

**Comment by GlenDC** [comment]
@robvanmieghem did you want to work on this issue by the way? I had unassigned it from you as I thought you had originally assigned it to yourself as you were thinking about a solution, and it seemed that your idea to link this with the tlogserver resolved that for you.

Also I had moved this to milestone alpha-4, as alpha-3 is already very full as it is.

But if any of this is wrong, than please do correct me.

**Comment by robvanmieghem** [comment]
>Instead of **fill** the slaves, we can also use tlog to **assist** the slaves.
> So, we can setup a slave, like the original plan. When the master is failing, we execute `tlogreplay` for the last X minutes. This way, the recovery will be much faster.

Was thinking about that too originally. Thing is you need to know more or less to what point the slave caught up, monitor the master slave replication, detect a failing master, trigger this process, put a new config next to the nbdserver and SIGHUP it, all without causing io errors in the vm using the nbdserver.

The redis replication (although it occurs more in blocks) also needs to send all the data over the network so that's why I thought we might just as well replicate them from the tlogserver since this adds the benefit of the tlogserver knowing if they are up to date.

If the nbdserver has a failing master connection, it can ask the tlog to flush to the slaves and continue directly without a hickup for the consuming vm. It also does not have to wait for an external slow process of detecting failure and repairing it.

> But if we don't have time constraint, we can simply do `tlogreplay` from the beginning.

We do, io's will time out.

**Comment by iwanbk** [comment]
> If the nbdserver has a failing master connection, it can ask the tlog to flush to the slaves and continue directly without a hickup for the consuming vm. It also does not have to wait for an external slow process of detecting failure and repairing it.

Sounds better for me, to store the data to master, tlogserver has two alternatives:
- use ndbserver backend code, flush to slave right after tlog flush 
- use tlogreplay right after tlog flush

I prefer to use tlogreplay because we don't really need it to be super fast and we can do it in async way. It is also much more simpler than using nbdserver backend code

**Comment by robvanmieghem** [comment]
My initial idea was indeed to use the nbdserver backend code but indeed, tlogreplay might be more easy and does interfere with the nbdserver logic.

**Comment by GlenDC** [comment]
Using the tlogreplay to restore a vdisk sounds like a good idea, as it means that all data that is restored is also safe in the tlog storage servers.

However I don' think it should be the tlogserver that monitors the ardb servers to see if a master/slave fails, and do stuff around that, might be better suite for a service devoted to orchestrating all that. But yes, I do agree that that service should then use tlogreplay to restore the data onto the new storage server.

Not entirely sure if we can fit this into the deadline of this milestone though, seems like it might delay things, unless I am missing some obvious things, and it is in fact easier than I think.

**Comment by iwanbk** [comment]
> However I don' think it should be the tlogserver that monitors the ardb servers to see if a master/slave fails, 

The idea is for the nbdserver to detect failed master

> Not entirely sure if we can fit this into the deadline of this milestone though, seems like it might delay things, unless I am missing some obvious things, and it is in fact easier than I think.

I created tasks list of this issue, let me know if it doesn't make sense

**Comment by iwanbk** [comment]
My progress:
 

> tlog : add nbdserver's ardb slave config to server


i was a bit confused with config module, and still not sure what to do.
So, i'm still using existing code, in hacky way, should be fixed later.
The config is like this
```
storageClusters: # A required map of storage clusters,
                 # only 1 storage cluster is required
  mycluster: # Required (string) ID of this storage cluster
    dataStorage: # A required array of connection (dial)strings, used to store data
      - address: 127.0.0.1:16386 # At least 1 connection (dial)string is required,
    metadataStorage:
      address: 127.0.0.1:16387 # Required connection (dial)string,
  tlogCluster:
    dataStorage:
      - address: 127.0.0.1:16379
      - address: 127.0.0.1:16380
      - address: 127.0.0.1:16381
      - address: 127.0.0.1:16382
      - address: 127.0.0.1:16383
      - address: 127.0.0.1:16384
                                        
vdisks: # A required map of vdisks,
        # only 1 vdisk is required
  myimg: # Required (string) ID of this vdisk
    blockSize: 4096 # Required static (uint64) size of each block
    readOnly: false # Defines if this vdisk can be written to or not
                    # (optional, false by default)
    size: 10 # Required (uint64) total size in GiB of this vdisk
    storageCluster: mycluster # Required (string) ID of the storage cluster to use
                              # for this vdisk's storage, has to be a storage cluster
                              # defined in the `storageClusters` section of THIS config file
    type: boot # Required (VdiskType) type of this vdisk
    tlogStorageCluster: tlogCluster
```
Yes, it looks like a mix of tlog and nbd configs :). The nbd part is the ardb slave config.

>  tlog : also flush (using tlogreplay) to ardb slave in async way

The code itself is pretty simple:
- create another goroutine (in a different struct name `slaveSyncer`) to do tlogreplay to the slave
- after flushing, tlog send the aggregation object to `slaveSyncer`.
- `slaveSyncer` do tlog replay
- make new tlogreplay object, shared by `slaveSyncer` and `zeroctl resotre` command.

It is done, but unfortunately i got "import cycle" errors. Need to find a clean solution for this.

**Comment by iwanbk** [comment]
>  i got "import cycle" errors in the test code

tlogserver use tlog decoder
tlogdecoder use ardb
ardb's test use tlogserver
:D

**Comment by GlenDC** [comment]
> i was a bit confused with config module, and still not sure what to do.

Feel free to ask any questions you have with it, or describe what is not clear from the documentation and comments. Because this might mean that the (inline) documentation is not good enough.

**Comment by iwanbk** [comment]
> but unfortunately i got "import cycle" errors in the test code

I've fixed this by creating an intermediate object that holds the channel, for the communication between tlog flusher and tlog slave syncer. It is a kind of message queue.

There is still an issue : some block seems to be corrupted. The `block.Data` call is failed.
When converting 256MB of image, there are +-10 corrupted blocks.

**Comment by iwanbk** [comment]
Another issue is related to nbdserver lba, will check it later
```
panic: runtime error: index out of range

goroutine 24 [running]:
github.com/zero-os/0-Disk/nbdserver/lba.(*LBA).Get.func1(0xc420368300, 0xfffff43b532c1606, 0x0, 0x0, 0x0)
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/lba/lba.go:113 +0x114
github.com/zero-os/0-Disk/nbdserver/lba.(*LBA).Get(0xc420368300, 0xfffa1da9960b02eb, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/lba/lba.go:117 +0xbe
github.com/zero-os/0-Disk/nbdserver/ardb.(*dedupedStorage).Get(0xc420141d10, 0xfffa1da9960b02eb, 0xb96e9d, 0xc420368300, 0x1106a, 0x0, 0xc420055aa0)
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/deduped.go:101 +0x40
github.com/zero-os/0-Disk/nbdserver/ardb.(*Backend).mergeZeroes(0xc420368340, 0xfffa1da9960b02eb, 0xfffffffffffffbe8, 0x87778f7747dfe5d1, 0xb58649, 0xc4201f5770, 0x1900000078, 0x200000028, 0xfffffffffffffffe)
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/backend.go:93 +0x42
github.com/zero-os/0-Disk/nbdserver/ardb.(*Backend).WriteZeroesAt(0xc420368340, 0x11a9c00, 0xc420263f40, 0xa1da9960b02eabe8, 0x87778f7747dfe5d1, 0x1, 0xc4201f5770, 0x28000000b0)
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/backend.go:76 +0x9a
github.com/zero-os/0-Disk/tlog/tlogclient/player.(*Player).ReplayAggregation(0xc4203683c0, 0xc420541200, 0xc420055f10, 0x1)
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/tlog/tlogclient/player/player.go:138 +0x59a
github.com/zero-os/0-Disk/tlog/tlogserver/slavesync.(*slaveSyncer).run(0xc420368400)
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/tlog/tlogserver/slavesync/slave_sync.go:115 +0x1a5
created by github.com/zero-os/0-Disk/tlog/tlogserver/slavesync.newSlaveSyncer
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/tlog/tlogserver/slavesync/slave_sync.go:101 +0x21f
```

**Comment by iwanbk** [comment]
> There is still an issue : some block seems to be corrupted. The block.Data call is failed.
> The error:
> 
> replay agg failed: failed to get data block of offset=19476480, err=capnp: invalid pointer address module=global caller=slave_sync.go:116

I added some check to the aggregation object.
Before being sent to slave_syncer, the aggregation still valid, not corrupted at all.

Maybe we need to send it in encoded form  (as []byte) instead of capnp object.

**Comment by iwanbk** [comment]
> Maybe we need to send it in encoded form (as []byte) instead of capnp object.

It works this way.

Tested with this scenario:
- convert image
- run nbdserver again with synced slave
- run the image : OK

**Comment by iwanbk** [comment]
> Another issue is related to nbdserver lba, will check it later
> 
> panic: runtime error: index out of range
> 
> goroutine 24 [running]:
> github.com/zero-os/0-Disk/nbdserver/lba.(*LBA).Get.func1(0xc420368300, 0xfffff43b532c1606, 0x0, 0x0, 0x0)
>         /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/lba/lba.go:113 +0x114

This issue is gone, but i wonder why it panic

**Comment by iwanbk** [comment]
added this to tasks list
```
 tlog : slave syncer must be able to self heal in case of error
```

**Comment by iwanbk** [comment]
next :  
```
tlog : add command to sync the ardb slave
```
it do these:
- reject all transaction to this vdisk. 
- waiting for slave to finish the sync.

Unlike the existing async connection between tlog client and server, it might be better for this command and all subsequent control commands to use separate sync connection. It simplifies many things and doesn't need the performance gain of the async connection

**Comment by GlenDC** [comment]
> > Another issue is related to nbdserver lba, will check it later
> > panic: runtime error: index out of range
> > goroutine 24 [running]:
> > github.com/zero-os/0-Disk/nbdserver/lba.(*LBA).Get.func1(0xc420368300, 0xfffff43b532c1606, > 0x0, 0x0, 0x0)
> > /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/lba/lba.go:113 +0x114

> This issue is gone, but i wonder why it panicked

The LBA code doesn't have any out-of-range checks in place, as it assumes that the user (deduped storage), will never go out of index, as they should be created in a synced way like that in the `ardb.go` file. This does rely on the user specifying the correct `vdiskSize` via the nbd protocol. Which I guess should be done by the nbd client correctly anyhow, no?

How did you create both the lba and deduped object? Or was it just as part of a normal nbdserver run?

**Comment by iwanbk** [comment]
>  Which I guess should be done by the nbd client correctly anyhow, no?

Yep

> How did you create both the lba and deduped object? Or was it just as part of a normal nbdserver run?

It is similar with tlogreplay.
I don't think that it is a problem anymore. It could be simply caused by invalid (big) offset. Not sure, it was corrupted data anyway

**Comment by iwanbk** [comment]
> waiting for slave to finish the sync.

It is done, but not tested yet, so it is not really done :)

>  it might be better for this command and all subsequent control commands to use separate sync connection. It simplifies many things and doesn't need the performance gain of the async connection

After looking at capnp RPC and Go jsonrpc, with current code, sync connection need a lot of work, better to do it in separate issue.

I have created a basic test scenario, thanks to `restore` tests from glen.
My basic test scenario (copied from the test code skeleton)

```go
// TestSlaveSyncBasic test slave syncer in a very nice artificial environment.
func TestSlaveSyncBasic(t *testing.T) {
    t.Log("== Start tlogserver == ")

    t.Log("create inmemory redis pool for tlog")
    t.Log("create inmemory redis pool for ardb slave")
    t.Log("start the server")

    t.Log("== start nbdserver backend with tlog")

    t.Log("== generate some random data and write it to the nbdserver backend== ")

    t.Log("== validate all data are correct == ")

    t.Log("== send command to tlog to sync the slave==")
    // we can't do it from the backend,
    // but fortunately it is OK to use another tlog client
    // our tlog server should support multiple clients (in a limited way)

    t.Log("Start another nbdserver with slave pool")
    t.Log("== validate all data are correct == ")
}

```

**Comment by iwanbk** [comment]
Following test scenario is working on `slave_sync_command` branch.
- start tlog with slave syncer
- create nbd backend 1, connected to above tlog
- write some data to nbd 
- issue command to sync the slave (it is only waiting for the slave to be fully synced), using separate tlog client
- create  nbd backend 2, connected to the slave
- make sure backend 2 able to read all data written by backend 1

The ideal test scenario is above test, with these changes:
- no need to issue command using separate client. We need to destroy the master instead
- no need for 2nd backend, 1st backend should self heal

**Comment by iwanbk** [comment]
> tlog : on (re) start, make sure to keep ardb slave synced
>  tlog : slave syncer must be able to self heal in case of error
> 

I think it is better to merge above tasks into one.
When error happens, slave syncer simply restart itself.

Things to implement
- save last synced sequence to slave storage.
- on (re) start, compare last synced sequence with last flushed sequence
- if we left behind, catch up!

**Comment by iwanbk** [comment]
> tlog : on (re) start, make sure to keep ardb slave synced
> tlog : slave syncer must be able to self heal in case of error

the implementation can be found on `reliable-slave-sync` branch.
I'm still thinking about improving the tests.

**Comment by iwanbk** [comment]
the `reliable-slave-sync` is basically finished, except the test code.
I use the nbd backend code in test in wrong way, resulting in very high memory usage, caused OOM error in travis which can't be reproduced in my PC.

Here is the profiling of my test code, super bad memory usage
[wek.pdf](https://github.com/zero-os/0-Disk/files/1085307/wek.pdf)

**Comment by iwanbk** [comment]
> I use the nbd backend code in test in wrong way, resulting in very high memory usage, caused OOM error in travis which can't be reproduced in my PC.

After more checking, i already use it correctly.  The vdisk restore also shows similar result.
The profiling shows that it caused by `lba.NewLBA`.
What strange is : it only happens when tlog is used.

I disable the test for now, because it needs 6GB of RAM

**Comment by iwanbk** [comment]
> The profiling shows that it caused by lba.NewLBA.
> What strange is : it only happens when tlog is used.
> 
> I disable the test for now, because it needs 6GB of RAM

Found the real issue, it is the LBA! 
Stupid me to not really believed the profiling result. Spent almost a day to debug it.

I've fixed this issue by simply using DB nbd backend instead of Boot nbd backend.

Test code runs stable now and using less memory.

**Comment by iwanbk** [comment]
I've implemented all sub tasks in the original task lists. But i just found that we still need to add hot reload support to the slave syncer.
We need it to change and add the slave.

**Comment by iwanbk** [comment]
>  But i just found that we still need to add hot reload support to the slave syncer.

After some thinking and digging the code, i thinking the best way is not using hot reloading way, we can simply restart the slave syncer on SIGHUP

The considerations:
- we need direct access to the nbdserver's metadata storage, as far as i can see from the code, there is no hot reload support for this
- we can enable/disable slave syncer on SIGHUP

**Comment by iwanbk** [comment]
all sub tasks has been implemented
